# Generated by Django 5.0.7 on 2024-07-25 18:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do convidado')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado?')),
                ('confirmed_at', models.DateTimeField(verbose_name='Data de confirmação')),
            ],
        ),
    ]
