# Generated by Django 5.0.7 on 2024-07-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de confirmação'),
        ),
    ]
