# Generated by Django 5.0.7 on 2024-07-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_guest_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
