# Generated by Django 5.0.7 on 2024-07-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_guest_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'guest', 'verbose_name_plural': 'guests'},
        ),
        migrations.AlterModelTable(
            name='guest',
            table='tb_guests',
        ),
    ]
