# Generated by Django 5.0.7 on 2024-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_alter_guest_options_alter_guest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de confirmação'),
        ),
    ]
