# Generated by Django 5.0.7 on 2024-07-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_alter_guest_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TunnelmoleURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
